# Form implementation generated from reading ui file 'userDefined.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

from userDefinedFuncs import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1118, 895)
        MainWindow.setStyleSheet("background-color:gray\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.userdeflbl = QtWidgets.QLabel(parent=self.centralwidget)
        self.userdeflbl.setGeometry(QtCore.QRect(480, 10, 121, 16))
        self.userdeflbl.setObjectName("userdeflbl")
        self.biseclbl = QtWidgets.QLabel(parent=self.centralwidget)
        self.biseclbl.setGeometry(QtCore.QRect(520, 40, 121, 16))
        self.biseclbl.setObjectName("biseclbl")
        self.fxlbl = QtWidgets.QLabel(parent=self.centralwidget)
        self.fxlbl.setGeometry(QtCore.QRect(530, 80, 121, 16))
        self.fxlbl.setObjectName("fxlbl")
        self.errorlbl = QtWidgets.QLabel(parent=self.centralwidget)
        self.errorlbl.setGeometry(QtCore.QRect(530, 160, 121, 16))
        self.errorlbl.setObjectName("errorlbl")
        self.errortxt = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.errortxt.setGeometry(QtCore.QRect(360, 190, 381, 21))
        self.errortxt.setObjectName("errortxt")
        self.albl = QtWidgets.QLabel(parent=self.centralwidget)
        self.albl.setGeometry(QtCore.QRect(540, 230, 121, 16))
        self.albl.setObjectName("albl")
        
        # a textbox

        self.atxt = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.atxt.setGeometry(QtCore.QRect(360, 260, 381, 21))
        self.atxt.setObjectName("atxt")
        
        self.blbl = QtWidgets.QLabel(parent=self.centralwidget)
        self.blbl.setGeometry(QtCore.QRect(540, 310, 121, 16))
        self.blbl.setObjectName("blbl")
        
        # b textbox

        self.btxt = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.btxt.setGeometry(QtCore.QRect(360, 340, 381, 21))
        self.btxt.setObjectName("btxt")
        
        self.cnlbl = QtWidgets.QLabel(parent=self.centralwidget)
        self.cnlbl.setGeometry(QtCore.QRect(540, 490, 121, 16))
        self.cnlbl.setObjectName("cnlbl")
        
        # iteration or epsilon
        
        self.nOrIterTxt = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.nOrIterTxt.setGeometry(QtCore.QRect(360, 430, 381, 21))
        self.nOrIterTxt.setReadOnly(True)
        self.nOrIterTxt.setObjectName("nOrIterTxt")
       
       
        self.fcnlbl = QtWidgets.QLabel(parent=self.centralwidget)
        self.fcnlbl.setGeometry(QtCore.QRect(530, 570, 121, 16))
        self.fcnlbl.setObjectName("fcnlbl")
       
        # Cn textbox

        self.cnTxt = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.cnTxt.setGeometry(QtCore.QRect(360, 520, 381, 21))
        self.cnTxt.setReadOnly(True)
        self.cnTxt.setObjectName("cnTxt")
        
        self.nlbl = QtWidgets.QLabel(parent=self.centralwidget)
        self.nlbl.setGeometry(QtCore.QRect(540, 410, 121, 16))
        self.nlbl.setObjectName("nlbl")
        
        # F(Cn) textbox

        self.fcnTxt = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.fcnTxt.setGeometry(QtCore.QRect(360, 600, 381, 21))
        self.fcnTxt.setObjectName("fcnTxt")
        
        # compute button

        self.compbtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.compbtn.setGeometry(QtCore.QRect(300, 670, 111, 41))
        self.compbtn.setObjectName("compbtn")
        
        # reset button

        self.resbtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.resbtn.setGeometry(QtCore.QRect(690, 670, 111, 41))
        self.resbtn.setObjectName("resbtn")

        
        
        self.method = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.method.setGeometry(QtCore.QRect(40, 100, 120, 80))
        self.method.setObjectName("method")
        
        # method radiobuttons

        self.bisecrb = QtWidgets.QRadioButton(parent=self.method)
        self.bisecrb.setGeometry(QtCore.QRect(10, 20, 95, 20))
        self.bisecrb.setObjectName("bisecrb")
        
        self.secrb = QtWidgets.QRadioButton(parent=self.method)
        self.secrb.setGeometry(QtCore.QRect(10, 50, 95, 20))
        self.secrb.setObjectName("secrb")
        
        self.approach = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.approach.setGeometry(QtCore.QRect(40, 210, 120, 80))
        self.approach.setObjectName("approach")
        
        # approach method

        self.iterb = QtWidgets.QRadioButton(parent=self.approach) 
        self.iterb.setGeometry(QtCore.QRect(10, 20, 95, 20))
        self.iterb.setObjectName("iterb")
        
        self.tolrb = QtWidgets.QRadioButton(parent=self.approach)
        self.tolrb.setGeometry(QtCore.QRect(10, 50, 95, 20))
        self.tolrb.setObjectName("tolrb")
        

        # function textbox

        self.functxt = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.functxt.setGeometry(QtCore.QRect(360, 120, 381, 21))
        self.functxt.setObjectName("functxt")
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1118, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.bisecrb.toggled.connect(lambda: self.methodCheck(self.bisecrb, self.secrb))
        self.secrb.toggled.connect(lambda: self.methodCheck(self.bisecrb, self.secrb))

        self.iterb.toggled.connect(lambda: self.approachCheck(self.iterb, self.tolrb))
        self.tolrb.toggled.connect(lambda: self.approachCheck(self.iterb, self.tolrb))


        self.resbtn.clicked.connect(lambda: self.reset(self.functxt, self.errortxt, self.atxt, self.btxt, self.nOrIterTxt, self.cnTxt, self.fcnTxt))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.userdeflbl.setText(_translate("MainWindow", "User-Defined Section"))
        self.biseclbl.setText(_translate("MainWindow", "Bisection"))
        self.fxlbl.setText(_translate("MainWindow", "f(x)"))
        self.errorlbl.setText(_translate("MainWindow", "Error"))
        self.albl.setText(_translate("MainWindow", "A"))
        self.blbl.setText(_translate("MainWindow", "B"))
        self.cnlbl.setText(_translate("MainWindow", "Cn"))
        self.fcnlbl.setText(_translate("MainWindow", "F(Cn)"))
        self.nlbl.setText(_translate("MainWindow", "N"))
        self.compbtn.setText(_translate("MainWindow", "Compute"))
        self.resbtn.setText(_translate("MainWindow", "Reset"))
        self.method.setTitle(_translate("MainWindow", "Methods"))
        self.bisecrb.setText(_translate("MainWindow", "Bisection"))
        self.secrb.setText(_translate("MainWindow", "Secant"))
        self.approach.setTitle(_translate("MainWindow", "Approach"))
        self.iterb.setText(_translate("MainWindow", "Iterative"))
        self.tolrb.setText(_translate("MainWindow", "Tolerative"))

        self.compbtn.clicked.connect(lambda: self.bisectOrSecant(self.bisecrb, self.secrb, self.iterb, self.tolrb))
#============================================================================


    def reset(self, tf1, tf2, tf3, tf4, tf5, tf6, tf7):
        self.resbtn.clicked.connect(tf1.clear)
        self.resbtn.clicked.connect(tf2.clear)
        self.resbtn.clicked.connect(tf3.clear)
        self.resbtn.clicked.connect(tf4.clear)
        self.resbtn.clicked.connect(tf5.clear)
        self.resbtn.clicked.connect(tf6.clear)
        self.resbtn.clicked.connect(tf7.clear)



    def methodCheck(self, button1, button2):
        if button1.isChecked():
            self.albl.setText("A")
            self.blbl.setText("B")   
        elif button2.isChecked():
            self.albl.setText("x0")
            self.blbl.setText("x1")

    def  approachCheck(self, button1, button2):
        if button1.isChecked():
            self.errorlbl.setText("Iteration")
            self.nlbl.setText("Epsilon")

        elif button2.isChecked():
            self.errorlbl.setText("Error")
            self.nlbl.setText("N")

    def bisectiteration(self):
 
        userFunction = self.functxt.toPlainText()

        valueOfA = int(self.atxt.toPlainText())
        valueOfB = int(self.btxt.toPlainText())

        iterationValue = int(self.errortxt.toPlainText())

        root = bisectIterative(valueOfA, valueOfB, userFunction, iterationValue)
        funcRoot = function(userFunction, root[0])

        self.cnTxt.setText(str(root[0]))
        self.fcnTxt.setText(str(funcRoot))
        self.nOrIterTxt.setText(str(root[1]))

    def bisecepsilon(self):
        userFunction = self.functxt.toPlainText()

        valueOfA = int(self.atxt.toPlainText())
        valueOfB = int(self.btxt.toPlainText())

        errorValue = float(self.errortxt.toPlainText())

        root = bisectEpsilon(valueOfA, valueOfB, userFunction, errorValue)
        funcRoot = function(userFunction, root[0])

        self.cnTxt.setText(str(root[0]))
        self.fcnTxt.setText(str(funcRoot))
        self.nOrIterTxt.setText(str(root[1]))


    def secIterative(self):
        userFunction = self.functxt.toPlainText()

        aValue = int(self.atxt.toPlainText())
        bValue = int(self.btxt.toPlainText())

        iterationValue = int(self.errortxt.toPlainText())

        rootValue = secantIteration(aValue, bValue, userFunction, iterationValue)
        rootFunctionValue = function(userFunction,rootValue[0])

        self.cnTxt.setText(str(rootValue[0]))
        self.fcnTxt.setText(str(rootFunctionValue))
        self.nOrIterTxt.setText(str(rootValue[1]))  

    def secEpsilon(self):
        userFunction = self.functxt.toPlainText()

        aValue = int(self.atxt.toPlainText())
        bValue = int(self.btxt.toPlainText())

        errorValue = float(self.errortxt.toPlainText())

        rootValue = secantEpsilon(aValue, bValue, userFunction, errorValue)
        rootFunctionValue = function(userFunction,rootValue[0])

        self.cnTxt.setText(str(rootValue[0]))
        self.fcnTxt.setText(str(rootFunctionValue))
        self.nOrIterTxt.setText(str(rootValue[1]))  

    def bisectOrSecant(self, buttonA, buttonB, button1, button2):
        
        if buttonA.isChecked() and button1.isChecked():
           self.compbtn.clicked.connect(self.bisectiteration)

        elif buttonA.isChecked() and button2.isChecked():
            self.compbtn.clicked.connect(self.bisecepsilon)
        
        elif buttonB.isChecked() and button1.isChecked():
            self.compbtn.clicked.connect(self.secIterative)

        elif buttonB.isChecked() and button2.isChecked():
            self.compbtn.clicked.connect(self.secEpsilon)

    
   


#============================================================================

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
